coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 0.01
    patch: false
    changes: false
comment:
  layout: "header, diff, sunburst, uncovered"
  behavior: default
ignore:
  - "pylabianca/localize.py"
  - "pylabianca/postproc.py"
